# Site settings
title: Hardathon
description: "Первый железный хакатон в Ульяновске!"
email: hardathon@futurelab.space
url: https://hardathon.github.io

# Social networks usernames
social:
  - title: facebook
    url: https://www.facebook.com/events/1758370364390432/
  - title: vk
    url: http://vk.com/hardathon
